GET http://localhost:5000/transaksi

###
GET http://localhost:5000/transaksi/1

###
POST http://localhost:5000/transaksi
Content-Type: application/json

{
    "tanggal_transaksi": "2022-12-12",
    "kategori": "Pemasukan",
    "nominal": "100000",
    "keterangan": "uang penjualan kertas"
}

###
PATCH http://localhost:5000/transaksi/1
Content-Type: application/json

{
    "tanggal_transaksi": "2022-12-12",
    "kategori": "Pengeluaran",
    "nominal": "100000",
    "keterangan": "Pembelian kertas"
}

###
DELETE http://localhost:5000/transaksi/2